apiVersion: v2
name: kata-pulse-chart
description: Real-time metrics for Kata Containers - cadvisor-compatible monitoring agent
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - kata
  - containers
  - monitoring
  - metrics
  - prometheus
home: https://github.com/diverofdark/kata-pulse
sources:
  - https://github.com/diverofdark/kata-pulse
maintainers:
  - name: DiverOfDark
    url: https://github.com/diverofdark
